version: "3.0"
services:
  example_server:
    image: wei
    container_name: example_server
    build:
      context: .
      dockerfile: ./docker/Dockerfile-wei
    volumes:
      - ./work:/example/work
    ports:
      - 8000:8000
    command: python -m wei.server --workcell /example/work/example_workcell.yaml --redis_host example_redis
    depends_on:
      - example_redis

  example_scheduler:
    image: wei
    container_name: example_scheduler
    volumes:
      - ./work:/example/work
    command: python -m wei.scheduler --workcell /example/work/example_workcell.yaml --redis_host example_redis --server example_server
    depends_on:
      - example_redis
      - example_sleeper
      - example_webcam

  example_redis:
    image: redis
    container_name: example_redis
    ports:
      - 6379:6379
    volumes:
      - ~/.wei/redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

  example_sleeper:
    image: wei
    container_name: example_sleeper
    command: python /wei/examples/example_clients/sleep_rest_node.py
    ports:
      - 2000:2000

  example_webcam:
    image: wei
    container_name: example_webcam
    ports:
      - 2001:2001
    command: python /wei/examples/example_clients/webcam_rest_node.py

  example_jupyter:
    image: example_jupyter
    container_name: example_jupyter
    user: root
    working_dir: "/home/jovyan"
    build:
      context: .
      dockerfile: ./docker/Dockerfile-jupyter
      args:
        UID: ${UID}
        GID: ${GID}
        USER: jovyan
    ports:
      - 8888:8888
    volumes:
      - ./work:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "wei"
      NB_USER: "jovyan"
      CHOWN_HOME: "yes"
      NB_UID: "${UID}"
      NB_GID: "${GID}"
