version: "3.0"
services:
  starting_example_server:
    image: wei
    container_name: starting_example_server
    build:
      context: .
      dockerfile: ./docker/Dockerfile-wei
    ports:
      - 8000:8000
    command: python -m wei.server --workcell /wei/tests/test_workcell.yaml --redis_host starting_example_redis
    depends_on:
      - starting_example_redis
  starting_example_scheduler:
    image: wei
    container_name: starting_example_scheduler
    build:
      context: .
      dockerfile: ./docker/Dockerfile-wei
    command: python -m wei.scheduler --workcell /wei/tests/test_workcell.yaml --redis_host starting_example_redis --server starting_example_server
    depends_on:
      - starting_example_redis
      - starting_example_sleeper
      - starting_example_webcam
  starting_example_redis:
    image: redis
    container_name: starting_example_redis
    ports:
      - 6379:6379
    volumes:
      - ~/.wei/redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
  starting_example_sleeper:
    image: wei
    container_name: starting_example_sleeper
    build:
      context: .
      dockerfile: ./docker/Dockerfile-wei
    command: python /wei/examples/example_clients/sleep_rest_node.py
    ports:
      - 2000:2000
  starting_example_webcam:
    image: wei
    container_name: starting_example_webcam
    build:
      context: .
      dockerfile: ./docker/Dockerfile-wei
    ports:
      - 2001:2001
    command: python /wei/examples/example_clients/webcam_rest_node.py
  starting_example_jupyter:
    image: starting_example_jupyter
    container_name: starting_example_jupyter
    user: root
    working_dir: "/home/jovyan"
    build:
      context: .
      dockerfile: ./docker/Dockerfile-jupyter
      args:
        UID: ${UID}
        GID: ${GID}
        USER: jovyan
    ports:
      - 8888:8888
    volumes:
      - ./work:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "wei"
      NB_USER: "jovyan"
      CHOWN_HOME: "yes"
      NB_UID: "${UID}"
      NB_GID: "${GID}"
