FROM jupyter/datascience-notebook:latest
# USER root
ARG USER=jovyan
ARG UID=1000
ARG GID=1000
USER root

RUN mkdir -p /home/${USER}/wei
RUN mkdir -p /home/${USER}/.wei/temp
RUN chown -R ${UID}:${GID} /home/${USER}/.wei

# Clone wei files
RUN git clone https://github.com/AD-SDL/wei.git /home/${USER}/wei

# Install dependencies
RUN python -m pip install --upgrade pip
RUN pip install -r /home/${USER}/wei/requirements/requirements.txt
RUN pip install -r /home/${USER}/wei/requirements/dev.txt

# Install wei
RUN pip install -e /home/${USER}/wei
